In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('../data/Fish.csv')

data = df[['Weight','Length2','Length3','Height','Width']]  
target = df['Species']

train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=50, random_state=42
)

In [4]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)

train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [5]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9357798165137615
0.94


In [9]:
import numpy as np

print(lr.predict(test_scaled[:5]))
print(np.round(lr.predict_proba(test_scaled[:5]), decimals=3))

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']
[[0.    0.015 0.812 0.    0.16  0.009 0.003]
 [0.    0.003 0.049 0.    0.007 0.94  0.   ]
 [0.    0.    0.035 0.922 0.013 0.03  0.   ]
 [0.01  0.035 0.307 0.006 0.563 0.    0.078]
 [0.    0.    0.889 0.003 0.102 0.004 0.002]]
